// COMPLIANCE-LOCKED — DO NOT MODIFY
export const PDF_COPY = {
    title: 'Personal Income Summary',
    subtitle: 'User-generated report based on data visible on your dashboard',
    executiveSummary:
        "This document summarizes total earnings visible on the user's gig platform dashboard for the selected period.",
    dataSource:
        'Data Source: Earnings information visible to the user on their gig platform dashboard.',
    disclaimer:
        'This document is a user-generated income summary created for informational purposes only. GigProof does not verify, certify, audit, or guarantee any earnings.',
    footerTrustLine: 'Generated by GigProof • Privacy-first • No bank connections • No credential storage',
    labels: {
        reportingPeriod: 'Reporting Period',
        totalEarnings: 'TOTAL EARNINGS',
        fullName: 'Full Name',
        accountEmail: 'Account Email',
        platform: 'Platform',
        reportReference: 'Report Reference'
    }
};
